### ISSUE TITLE
Not working on Ubuntu

### ISSUE THREAD

**Issue by rektide** [sos4nt/dynamic-colors#13]
Hiya. I'm on 9.21 based on Ubuntu Vivid. Compile flags are: ` perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,smart-resize,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm`.

I've added the `urxvt*dynamicColors: on` Xresource, but the `echo -e "\033]11;#ff0000\007"` has no effect. Any thoughts? Any ideas what I can do to begin debugging this?

**Comment by rektide** [comment]
Switched from `rxvt-unicode-256colors` to `rxvt-unicode` and it works. Bah. Flags are the same.

**Comment by sos4nt** [comment]
This is / was probably because `rxvt-unicode-256colors` doesn't use the default ANSI colors.
